# Capstone Project – Python Fundamentals

## Objective
This notebook solves the given Python Fundamentals assessment using **Python, Pandas, and NumPy**.  
All tasks have been completed in sequence as instructed in the assessment, with outputs and explanations.

## Tools Used
- Python
- Pandas
- NumPy

In [1]:
!mamba install pandas numpy

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 5.850799999952316 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ pandas                        3.0.2                         np22py313h9d9dc1e_0           emscripten-forge
+ python-tzdata                 2025.3                        pyhd8ed1ab_0                  conda-forge
- pip                           25.3                          pyh145f28c_0                  conda-forge

In [2]:
# Importing required libraries
import pandas as pd
import numpy as np

# Task 1 — Create DataFrames and Save Them as CSV Files
In this task, we create the following three DataFrames from the assessment:
1. Employee DataFrame
2. Seniority Level DataFrame
3. Project DataFrame

After creating them, we save them as CSV files for use in subsequent tasks.

In [3]:
# Importing os to create a folder for saving CSV files
import os

# Creating a folder to store all CSV files
folder_name = "assessment_files"
os.makedirs(folder_name, exist_ok=True)

# Creating Employee DataFrame exactly as given in the PDF
employee_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],
    'Name': ['John Alter', 'Alice Luxumberg', 'Tom Sabestine', 'Nina Adgra', 'Amy Johny'],
    'Gender': ['M', 'F', 'M', 'F', 'F'],
    'City': ['Paris', 'London', 'Berlin', 'Newyork', 'Madrid'],
    'Age': [25, 27, 29, 31, 30]
}

# Converting employee data into a DataFrame
employee_df = pd.DataFrame(employee_data)

# Creating Seniority Level DataFrame exactly as given in the PDF
seniority_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],
    'Designation Level': [2, 2, 3, 2, 3]
}

# Converting seniority data into a DataFrame
seniority_df = pd.DataFrame(seniority_data)

# Creating Project DataFrame exactly as given in the PDF
project_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005', 'A002', 'A005', 'A003', 'A001', 'A003', 'A001', 'A004', 'A004', 'A005'],
    'Project': ['Project 1', 'Project 2', 'Project 3', 'Project 4', 'Project 5', 'Project 6', 'Project 7',
                'Project 8', 'Project 9', 'Project 10', 'Project 11', 'Project 12', 'Project 13', 'Project 14'],
    'Cost': [1002000, 2000000, 4500000, 5500000, np.nan, 680000, 400000, 350000, np.nan, 300000, 2000000, 1000000, 3000000, 200000],
    'Status': ['Finished', 'Ongoing', 'Finished', 'Ongoing', 'Finished', 'Failed', 'Finished',
               'Failed', 'Ongoing', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Finished']
}

# Converting project data into a DataFrame
project_df = pd.DataFrame(project_data)

# Displaying Employee DataFrame
print("Employee DataFrame:")
display(employee_df)

# Displaying Seniority Level DataFrame
print("Seniority Level DataFrame:")
display(seniority_df)

# Displaying Project DataFrame
print("Project DataFrame:")
display(project_df)

# Saving Employee DataFrame, Seniority Level DataFrame, Project DataFrame as CSV file inside the folder
employee_df.to_csv(f"{folder_name}/Employee.csv", index=False)
seniority_df.to_csv(f"{folder_name}/Seniority_Level.csv", index=False)
project_df.to_csv(f"{folder_name}/Project.csv", index=False)

# Printing confirmation message after saving all CSV files
print("All CSV files saved successfully inside the folder:", folder_name)

Employee DataFrame:

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

Seniority Level DataFrame:

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

Project DataFrame:

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

All CSV files saved successfully inside the folder: assessment_files

# Task 2 — Replace Missing Values in the Cost Column Using Running Average

In this task, we work with the **Project DataFrame**, where the **Cost** column contains some missing values.

Our objective is to:
1. identify the missing values in the **Cost** column
2. replace them using the **running average**
3. use a **for loop** as instructed in the assessment

In [14]:
# Reading the saved Project CSV file
project_df = pd.read_csv("assessment_files/Project.csv")

# Replacing missing Cost values using running average with a for loop
for i in range(len(project_df)):
    if pd.isna(project_df.loc[i, "Cost"]):
        running_average = project_df.loc[:i-1, "Cost"].mean()
        project_df.loc[i, "Cost"] = running_average

# Saving the updated Project DataFrame because later tasks must use the saved CSV files
project_df.to_csv("assessment_files/Project.csv", index=False)

# Displaying the updated Project DataFrame
print("Updated Project DataFrame after filling missing Cost values:")
display(project_df)

Updated Project DataFrame after filling missing Cost values:

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5  3250500.0  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9  2210312.5   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

# Task 3 — Split the Name Column into First Name and LastName

In this task, we work with the **Employee DataFrame**.

Our objective is to:
1. split the **Name** column into two new columns: **First Name** and **LastName**
2. remove the old **Name** column
3. display the updated DataFrame
4. save the updated changes back to the CSV file

In [5]:
# Reading the saved Employee CSV file
employee_df = pd.read_csv("assessment_files/Employee.csv")

# Displaying the Employee DataFrame before splitting the Name column
print("Employee DataFrame before splitting the Name column:")
display(employee_df)

# Splitting the Name column into First Name and LastName
employee_df[["First Name", "LastName"]] = employee_df["Name"].str.split(" ", n=1, expand=True)

# Dropping the old Name column
employee_df.drop(columns=["Name"], inplace=True)

# Rearranging the columns to place First Name and LastName after ID
employee_df = employee_df[["ID", "First Name", "LastName", "Gender", "City", "Age"]]

# Displaying the updated Employee DataFrame
print("Employee DataFrame after splitting the Name column:")
display(employee_df)

# Saving the updated Employee DataFrame back to CSV
employee_df.to_csv("assessment_files/Employee.csv", index=False)

Employee DataFrame before splitting the Name column:

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

Employee DataFrame after splitting the Name column:

     ID First Name   LastName Gender     City  Age
0  A001       John      Alter      M    Paris   25
1  A002      Alice  Luxumberg      F   London   27
2  A003        Tom  Sabestine      M   Berlin   29
3  A004       Nina      Adgra      F  Newyork   31
4  A005        Amy      Johny      F   Madrid   30

# Task 4 — Join All Three DataFrames into a Single DataFrame Named Final

In this task, we use the saved CSV files from the previous tasks.

Our objective is to:
1. read the **Employee**, **Seniority Level**, and **Project** CSV files
2. join all three DataFrames into one single DataFrame
3. name the final merged DataFrame as **Final**
4. display the merged result for verification

In [6]:
# Reading the saved CSV files
employee_df = pd.read_csv("assessment_files/Employee.csv")
seniority_df = pd.read_csv("assessment_files/Seniority_Level.csv")
project_df = pd.read_csv("assessment_files/Project.csv")

# Merging Employee DataFrame with Seniority Level DataFrame using ID
Final = pd.merge(employee_df, seniority_df, on="ID", how="inner")

# Merging the above result with Project DataFrame using ID
Final = pd.merge(Final, project_df, on="ID", how="inner")

# Displaying the final merged DataFrame
print("Final DataFrame after joining all three DataFrames:")
display(Final)

Final DataFrame after joining all three DataFrames:

,ID,First Name,LastName,Gender,City,Age,Designation Level,Project,Cost,Status
0,A001,John,Alter,M,Paris,25,2,Project 1,1002000.0,Finished
1,A001,John,Alter,M,Paris,25,2,Project 9,2210312.5,Ongoing
2,A001,John,Alter,M,Paris,25,2,Project 11,2000000.0,Failed
3,A002,Alice,Luxumberg,F,London,27,2,Project 2,2000000.0,Ongoing
4,A002,Alice,Luxumberg,F,London,27,2,Project 6,680000.0,Failed
5,A003,Tom,Sabestine,M,Berlin,29,3,Project 3,4500000.0,Finished
6,A003,Tom,Sabestine,M,Berlin,29,3,Project 8,350000.0,Failed
7,A003,Tom,Sabestine,M,Berlin,29,3,Project 10,300000.0,Finished
8,A004,Nina,Adgra,F,Newyork,31,2,Project 4,5500000.0,Ongoing
9,A004,Nina,Adgra,F,Newyork,31,2,Project 12,1000000.0,Ongoing
10,A004,Nina,Adgra,F,Newyork,31,2,Project 13,3000000.0,Finished
11,A005,Amy,Johny,F,Madrid,30,3,Project 5,3250500.0,Finished
12,A005,Amy,Johny,F,Madrid,30,3,Project 7,400000.0,Finished
13,A005,Amy,Johny,F,Madrid,30,3,Project 14,200000.0,Finished

# Task 5 — Add a Bonus Column in the Final DataFrame

In this task, we work with the **Final DataFrame** created in the previous step.

Our objective is to:
1. create a new column named **Bonus**
2. give a **5% bonus** based on **project cost**
3. apply this bonus **only to employees whose project status is "Finished"**
4. keep the bonus as **0** for all other project statuses

In [7]:
# Creating a new Bonus column based on project cost
Final["Bonus"] = np.where(Final["Status"] == "Finished", Final["Cost"] * 0.05, 0)

# Displaying the updated Final DataFrame
print("Final DataFrame after adding the Bonus column:")
display(Final)

Final DataFrame after adding the Bonus column:

,ID,First Name,LastName,Gender,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,John,Alter,M,Paris,25,2,Project 1,1002000.0,Finished,50100.0
1,A001,John,Alter,M,Paris,25,2,Project 9,2210312.5,Ongoing,0.0
2,A001,John,Alter,M,Paris,25,2,Project 11,2000000.0,Failed,0.0
3,A002,Alice,Luxumberg,F,London,27,2,Project 2,2000000.0,Ongoing,0.0
4,A002,Alice,Luxumberg,F,London,27,2,Project 6,680000.0,Failed,0.0
5,A003,Tom,Sabestine,M,Berlin,29,3,Project 3,4500000.0,Finished,225000.0
6,A003,Tom,Sabestine,M,Berlin,29,3,Project 8,350000.0,Failed,0.0
7,A003,Tom,Sabestine,M,Berlin,29,3,Project 10,300000.0,Finished,15000.0
8,A004,Nina,Adgra,F,Newyork,31,2,Project 4,5500000.0,Ongoing,0.0
9,A004,Nina,Adgra,F,Newyork,31,2,Project 12,1000000.0,Ongoing,0.0
10,A004,Nina,Adgra,F,Newyork,31,2,Project 13,3000000.0,Finished,150000.0
11,A005,Amy,Johny,F,Madrid,30,3,Project 5,3250500.0,Finished,162525.0
12,A005,Amy,Johny,F,Madrid,30,3,Project 7,400000.0,Finished,20000.0
13,A005,Amy,Johny,F,Madrid,30,3,Project 14,200000.0,Finished,10000.0

# Task 6 — Demote Designation Level for Failed Projects and Delete Ineligible Employees

In this task, we work with the **Final DataFrame**.

Our objective is to:
1. identify the employees whose project status is **Failed**
2. demote their **Designation Level** by 1
3. delete the employee records whose **Designation Level** becomes more than 4
4. display the updated DataFrame

**Note:** As per the assessment, **1 is the highest designation** and **4 is the lowest**. So, **demotion** means moving to a lower rank, which is why the **Designation Level is increased by 1**. If it becomes **greater than 4**, the employee is treated as ineligible and removed.

In [8]:
# Finding employee IDs whose project status is Failed
failed_ids = Final.loc[Final["Status"] == "Failed", "ID"].unique()

# Demoting designation level by 1 for those employees
Final.loc[Final["ID"].isin(failed_ids), "Designation Level"] = Final.loc[
    Final["ID"].isin(failed_ids), "Designation Level"
] + 1

# Deleting employee records whose designation level is above 4
Final = Final[Final["Designation Level"] <= 4]

# Displaying the updated Final DataFrame
print("Final DataFrame after updating Designation Level and removing ineligible employees:")
display(Final)

Final DataFrame after updating Designation Level and removing ineligible employees:

,ID,First Name,LastName,Gender,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,John,Alter,M,Paris,25,3,Project 1,1002000.0,Finished,50100.0
1,A001,John,Alter,M,Paris,25,3,Project 9,2210312.5,Ongoing,0.0
2,A001,John,Alter,M,Paris,25,3,Project 11,2000000.0,Failed,0.0
3,A002,Alice,Luxumberg,F,London,27,3,Project 2,2000000.0,Ongoing,0.0
4,A002,Alice,Luxumberg,F,London,27,3,Project 6,680000.0,Failed,0.0
5,A003,Tom,Sabestine,M,Berlin,29,4,Project 3,4500000.0,Finished,225000.0
6,A003,Tom,Sabestine,M,Berlin,29,4,Project 8,350000.0,Failed,0.0
7,A003,Tom,Sabestine,M,Berlin,29,4,Project 10,300000.0,Finished,15000.0
8,A004,Nina,Adgra,F,Newyork,31,2,Project 4,5500000.0,Ongoing,0.0
9,A004,Nina,Adgra,F,Newyork,31,2,Project 12,1000000.0,Ongoing,0.0
10,A004,Nina,Adgra,F,Newyork,31,2,Project 13,3000000.0,Finished,150000.0
11,A005,Amy,Johny,F,Madrid,30,3,Project 5,3250500.0,Finished,162525.0
12,A005,Amy,Johny,F,Madrid,30,3,Project 7,400000.0,Finished,20000.0
13,A005,Amy,Johny,F,Madrid,30,3,Project 14,200000.0,Finished,10000.0

# Task 7 — Add Mr. and Mrs. to the First Name Column and Drop the Gender Column

In this task, we work with the **Final DataFrame**.

Our objective is to:
1. add **"Mr."** before the first name of male employees
2. add **"Mrs."** before the first name of female employees
3. remove the **Gender** column from the DataFrame
4. display the updated result

In [9]:
# Adding Mr. and Mrs. to the First Name column based on Gender
Final["First Name"] = np.where(
    Final["Gender"] == "M",
    "Mr. " + Final["First Name"],
    "Mrs. " + Final["First Name"]
)

# Dropping the Gender column
Final.drop(columns=["Gender"], inplace=True)

# Displaying the updated Final DataFrame
print("Final DataFrame after updating First Name and dropping Gender column:")
display(Final)

Final DataFrame after updating First Name and dropping Gender column:

,ID,First Name,LastName,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,Mr. John,Alter,Paris,25,3,Project 1,1002000.0,Finished,50100.0
1,A001,Mr. John,Alter,Paris,25,3,Project 9,2210312.5,Ongoing,0.0
2,A001,Mr. John,Alter,Paris,25,3,Project 11,2000000.0,Failed,0.0
3,A002,Mrs. Alice,Luxumberg,London,27,3,Project 2,2000000.0,Ongoing,0.0
4,A002,Mrs. Alice,Luxumberg,London,27,3,Project 6,680000.0,Failed,0.0
5,A003,Mr. Tom,Sabestine,Berlin,29,4,Project 3,4500000.0,Finished,225000.0
6,A003,Mr. Tom,Sabestine,Berlin,29,4,Project 8,350000.0,Failed,0.0
7,A003,Mr. Tom,Sabestine,Berlin,29,4,Project 10,300000.0,Finished,15000.0
8,A004,Mrs. Nina,Adgra,Newyork,31,2,Project 4,5500000.0,Ongoing,0.0
9,A004,Mrs. Nina,Adgra,Newyork,31,2,Project 12,1000000.0,Ongoing,0.0
10,A004,Mrs. Nina,Adgra,Newyork,31,2,Project 13,3000000.0,Finished,150000.0
11,A005,Mrs. Amy,Johny,Madrid,30,3,Project 5,3250500.0,Finished,162525.0
12,A005,Mrs. Amy,Johny,Madrid,30,3,Project 7,400000.0,Finished,20000.0
13,A005,Mrs. Amy,Johny,Madrid,30,3,Project 14,200000.0,Finished,10000.0

# Task 8 — Promote Designation Level by 1 for Employees Whose Age is More Than 29 Years

In this task, we continue working with the **Final DataFrame**.

Our objective is to:
1. identify the employees whose **Age** is more than **29**
2. promote their **Designation Level** by **1**
3. use an **if condition** as mentioned in the assessment
4. display the updated DataFrame

**Note:** As per the assessment, **1 is the highest designation** and **4 is the lowest**. So, **promotion** means moving to a higher rank, which is why the **Designation Level is decreased by 1**.

In [10]:
# Promoting designation level by 1 for employees whose age is more than 29
for i in range(len(Final)):
    if Final.loc[i, "Age"] > 29:
        Final.loc[i, "Designation Level"] = Final.loc[i, "Designation Level"] - 1

# Displaying the updated Final DataFrame
print("Final DataFrame after promoting Designation Level for employees above 29 years of age:")
display(Final)

Final DataFrame after promoting Designation Level for employees above 29 years of age:

,ID,First Name,LastName,City,Age,Designation Level,Project,Cost,Status,Bonus
0,A001,Mr. John,Alter,Paris,25,3,Project 1,1002000.0,Finished,50100.0
1,A001,Mr. John,Alter,Paris,25,3,Project 9,2210312.5,Ongoing,0.0
2,A001,Mr. John,Alter,Paris,25,3,Project 11,2000000.0,Failed,0.0
3,A002,Mrs. Alice,Luxumberg,London,27,3,Project 2,2000000.0,Ongoing,0.0
4,A002,Mrs. Alice,Luxumberg,London,27,3,Project 6,680000.0,Failed,0.0
5,A003,Mr. Tom,Sabestine,Berlin,29,4,Project 3,4500000.0,Finished,225000.0
6,A003,Mr. Tom,Sabestine,Berlin,29,4,Project 8,350000.0,Failed,0.0
7,A003,Mr. Tom,Sabestine,Berlin,29,4,Project 10,300000.0,Finished,15000.0
8,A004,Mrs. Nina,Adgra,Newyork,31,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Mrs. Nina,Adgra,Newyork,31,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Mrs. Nina,Adgra,Newyork,31,1,Project 13,3000000.0,Finished,150000.0
11,A005,Mrs. Amy,Johny,Madrid,30,2,Project 5,3250500.0,Finished,162525.0
12,A005,Mrs. Amy,Johny,Madrid,30,2,Project 7,400000.0,Finished,20000.0
13,A005,Mrs. Amy,Johny,Madrid,30,2,Project 14,200000.0,Finished,10000.0

# Task 9 — Add the Cost of All Projects for Each Employee in a New DataFrame “TotalProjCost”

In this task, we work with the **Final DataFrame**.

Our objective is to:
1. calculate the **total cost of all projects** for each employee
2. create a new DataFrame named **TotalProjCost**
3. keep only these three columns:
   - **ID**
   - **First Name**
   - **Total cost**
4. display the final result

In [11]:
# Creating a new DataFrame with total project cost for each employee
TotalProjCost = Final.groupby(["ID", "First Name"], as_index=False)["Cost"].sum()

# Renaming the Cost column to Total cost
TotalProjCost.rename(columns={"Cost": "Total cost"}, inplace=True)

# Displaying the TotalProjCost DataFrame
print("TotalProjCost DataFrame:")
display(TotalProjCost)

TotalProjCost DataFrame:

     ID  First Name  Total cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

# Task 10 — Print Employee Details Whose City Name Contains the Letter “o”

In this task, we work with the employee details available in the current DataFrame.

Our objective is to:
1. identify all records where the **City** name contains the letter **"o"**
2. filter those employee details
3. display the final result

In [12]:
# Filtering employee details whose city name contains the letter "o"
filtered_employees = Final[Final["City"].str.contains("o", case=False, na=False)]

# Displaying the filtered employee details
print('Employee details whose city name contains the letter "o":')
display(filtered_employees)

Employee details whose city name contains the letter "o":

,ID,First Name,LastName,City,Age,Designation Level,Project,Cost,Status,Bonus
3,A002,Mrs. Alice,Luxumberg,London,27,3,Project 2,2000000.0,Ongoing,0.0
4,A002,Mrs. Alice,Luxumberg,London,27,3,Project 6,680000.0,Failed,0.0
8,A004,Mrs. Nina,Adgra,Newyork,31,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Mrs. Nina,Adgra,Newyork,31,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Mrs. Nina,Adgra,Newyork,31,1,Project 13,3000000.0,Finished,150000.0